spring:
  application:
    name: file-management-service
  data.mongodb:
    uri: "mongodb+srv://codebuddy-test:Test123@cluster0.cfmd8.mongodb.net/codebuddy"

info:
  app:
    name: Codebuddy File Management Service
    description: File Management Service for Codebuddy
    version: 1.0.0

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


